<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8dkzih\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8dkzih/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerY8dkzih.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerY8dkzih\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerY8dkzih\appProdProjectContainer(array(
    'container.build_hash' => 'Y8dkzih',
    'container.build_id' => 'a241e29c',
    'container.build_time' => 1543431605,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8dkzih');
